################################################################
## Ragged Jack Farm                                           ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
homeassistant:
  name: Ragged Jack Mtn
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_time_zone

  customize: !include customizations.yaml
  packages: !include_dir_named packages

frontend:   
  javascript_version: latest
  themes: !include_dir_merge_named themes
updater:
  include_used_components: true
logger:
#http:
logbook:
recorder:
  exclude:
    domains:
      - sensor
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_select
map: 
sun: 
config:
conversation:
discovery:
system_health:
history:
  include:
    domains:
      - sensor
  exclude:
    entities: 
      - sensor.date
      - sensor.time
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
hacs:
  token: !secret hacs_token
lovelace: 
  mode: yaml
mobile_app: