################################################################
## Ragged Jack Farm                                           ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
homeassistant:
  name: Ragged Jack Mtn
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_time_zone

  customize: !include customizations.yaml
  packages: !include_dir_named packages

# Frontend Configs
frontend:   
  javascript_version: latest
  themes: !include_dir_merge_named themes

# Updater Config
updater:
  include_used_components: true

# Logger Config
logger:

# HTTP Config
#http:

# Logbook Config
logbook:

# History Config
history:

# Map Config
map: 

# Aun Config
sun: 

# Stock Config
config:

# Conversation Config
conversation:

# Discovery Config
discovery:

# System Health Config
system_health:

# HACS Config
hacs:
  token: !secret hacs_token

# Mobile App Config
mobile_app: