################################################################
## Ragged Jack Farm                                           ##
## Package: Lovelace UI                                       ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
# resources: !include lovelace/resources.yaml
  
animated_background: !include lovelace/animated_background.yaml

title: Ragged Jack Mtn

custom_header:
  compact_mode: true

views:
  # Home View
  - !include lovelace/views/home.yaml
  # Power Center View
  - !include lovelace/views/power_center.yaml  
  # PV System View
  - !include lovelace/views/pv_array.yaml
  # Generator Management View
  - !include lovelace/views/generac.yaml
  # Stock And Finances
  - !include lovelace/views/finance.yaml
  # Media Control View
  - !include lovelace/views/media.yaml
  # System Monitor View
  - !include lovelace/views/system_monitor.yaml