################################################################
## Ragged Jack Farm                                           ##
## Package: Lovelace UI                                       ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
resources: !include ui/resources.yaml
  
animated_background:
  default_url: /local/background-animations/sunny.html
  entity: "sensor.storm_center"
  state_url:
      'sunny': /local/background-animations/sunny.html
      'partlycloudy': /local/background-animations/cloudy.html
      'cloudy': /local/background-animations/cloudy.html
      'mostlycloudy': /local/background-animations/mostlycloudy.html
      'clear-night': /local/background-animations/night.html
      'fog': /local/background-animations/fog.html

title: Ragged Jack Mtn
views:
  ################################################################
  ## Home View ###################################################
  ################################################################
  - !include ui/home.yaml
  ################################################################
  ## Power Center View ###########################################
  ################################################################
  - !include ui/power_center.yaml  
  ################################################################
  ## PV System View ##############################################
  ################################################################
  - !include ui/pv_array.yaml
  ################################################################
  ## Generator Management View ###################################
  ################################################################
  - !include ui/generac.yaml
  ################################################################
  ## Media Control View ##########################################
  ################################################################ 
  - !include ui/media.yaml
  ################################################################
  ## System Monitor View #########################################
  ################################################################
  - !include ui/system_monitor.yaml