################################################################
## Ragged Jack Farm                                           ##
## Package: Sun2 Integrsation                                 ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
homeassistant:
  customize:
      package.node_anchors:
        customize: &customize
          package: 'sun2'
sensor:
  ########
  # Moon #
  ########
  - platform: moon

  #################
  # Date and Time #
  #################
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
      
  #########
  # Sun 2 #
  #########s
  - platform: sun2
    monitored_conditions:
      - solar_midnight
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - daylight
      - night
      - elevation
      - max_elevation
binary_sensor:
  - platform: sun2
    monitored_conditions:
      - elevation