################################################################
## Ragged Jack Farm                                           ##
## Package: Weather                                           ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
homeassistant:
  customize:
      package.node_anchors:
        customize: &customize
          package: 'weather'

################################################################
# DarkSky                                                      #
################################################################
weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

sensor:
  # PV related forecasts
  - platform: darksky
    name: pv
    api_key: !secret darksky_key
    forecast:
      - 0
      - 1
    hourly_forecast:
      - 0
      - 1
      - 2
      - 3
    monitored_conditions:
      - cloud_cover
      - visibility

  # Storm related forecasts
  - platform: darksky
    name: storm_center
    api_key: !secret darksky_key
    scan_interval: '01:00:00'
    monitored_conditions:
      - nearest_storm_distance
      - nearest_storm_bearing
      - alerts
      - precip_type
      - precip_intensity
      - precip_accumulation
      - temperature
      - apparent_temperature
      - wind_speed
      - wind_bearing

################################################################
# Template Sensors                                             #
################################################################
  - platform: template
    sensors:
      # Wind Direction degrees to compass points
      storm_center_wind_direction:
        friendly_name: Wind Direction
        value_template: >
          {% set deg = states('sensor.storm_center_wind_bearing')|float(0) %}
          {% set abr = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'] %}
          {%- set i = ((deg/22.5)| round(0))| int %}
          {%- set i = 0 if i == 16 else i %}
          {{ abr[i] }}

      # Storm Direction degrees to compass points
      storm_center_storm_direction:
        friendly_name: Wind Direction
        value_template: >
          {% set deg = states('sensor.storm_center_nearest_storm_bearing')|float(0) %}
          {% set abr = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'] %}
          {%- set i = ((deg/22.5)| round(0))| int %}
          {%- set i = 0 if i == 16 else i %}
          {{ abr[i] }}
################################################################
# Input Booleans                                               #
################################################################
input_boolean:
  # Is precipitating
  storm_center_is_precipitating:
    name: Is Precipitating
    initial: false
