################################################################
## Ragged Jack Farm                                           ##
## Package: Weather Alerts                                        ##
## Author: David Durost <david.durost@gmail.com>              ##
## Url: http://ragedjackfarm.net                              ##
################################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'weather_alerts'
    sensor.nws_alert_count:
      friendly_name: Alerts
      icon: mdi:alert-outline

sensor:
  - platform: template
    sensors:
      storm_center_alert_text:
        entity_id: sensor.storm_center_alerts
        friendly_name: 'Weather Alert Text'
        value_template: >-
          {% if is_state('sensor.storm_center_alerts','0') %}
            No Weather Alerts
          {% elif is_state('sensor.storm_center_alerts','1') %}
            {{ states.sensor.storm_center_alerts.attributes.title }}
          {% else %}
            {{ states.sensor.storm_center_alerts.attributes.title_0 }}
          {% endif %}